"""Mock inference: deterministic structured observation without GPU."""

from __future__ import annotations

import time

from core.cancel import get_global_token
from core.config import AppConfig
from core.logging import get_logger, log_event
from core.models import (
    InferenceRequest,
    InferenceResponse,
    ScreenFrame,
    ScreenObservation,
    UIVisionResult,
)

from inference.base import InferenceBackend

_log = get_logger("inference.mock")


class MockInference(InferenceBackend):
    def __init__(self, config: AppConfig) -> None:
        self.config = config

    def health(self) -> bool:
        return True

    def observe(
        self,
        frame: ScreenFrame,
        vision: UIVisionResult,
        *,
        user_goal: str,
        trace_id: str = "",
    ) -> InferenceResponse:
        get_global_token().check()
        t0 = time.perf_counter()
        req = InferenceRequest(
            trace_id=trace_id,
            frame_id=frame.frame_id,
            task=user_goal,
            ui_summary=[
                {
                    "element_id": e.element_id,
                    "type": e.type.value,
                    "text": e.text,
                    "clickable": e.clickable,
                }
                for e in vision.elements
            ],
            has_image=bool(frame.image_b64 or frame.image_path),
            max_tokens=self.config.inference.max_tokens,
            temperature=self.config.inference.temperature,
        )
        log_event(
            _log,
            "inference.request",
            request_id=req.request_id,
            trace_id=trace_id,
            frame_id=frame.frame_id,
            task_preview=user_goal[:80],
            element_count=len(vision.elements),
        )

        time.sleep(0.02)
        clickable = [e for e in vision.elements if e.clickable]
        obs_text = (
            f"Mock screen {frame.width}x{frame.height}: "
            f"{len(vision.elements)} elements, {len(clickable)} clickable. "
            f"User goal: {user_goal}"
        )
        observation = ScreenObservation(
            trace_id=trace_id,
            frame_id=frame.frame_id,
            observation=obs_text,
            ui_elements=vision.elements[:6],
            notes="generated by MockInference (Phase B)",
            confidence=0.9,
            model_name="mock-qwen3.5-2b",
            latency_ms=(time.perf_counter() - t0) * 1000,
        )
        resp = InferenceResponse(
            request_id=req.request_id,
            trace_id=trace_id,
            ok=True,
            observation=observation,
            raw_text=observation.model_dump_json(),
            latency_ms=observation.latency_ms,
        )
        log_event(_log, "inference.response", **resp.log_summary())
        return resp
